.TH OpenZWAVE 1
.SH NAME
MinOZW \- a small test application for libopenzwave
.SH SYNOPSIS
.nf
.B MinOZW [port]
.fi
.
.SH DESCRIPTION
.rs
.sp
MinOZW is just a small example to test the openZWAVE library.
The first argument is the port where the ZWAVE controller is attached to. The default value is /dev/ttyUSB0.

